import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  StatusBar,
  Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { usePassingPackageStore } from '../store/usePassingPackageStore';

export const PackageEmptyStateScreen: React.FC = () => {
  const router = useRouter();
  const { activeBranch, activeSemester } = usePassingPackageStore();

  const handleRequestPackage = () => {
    Alert.alert(
      'Package Requested!',
      `Thank you! Your request for VTU ${activeBranch} Semester ${activeSemester} Passing Package has been submitted to the content team.`,
      [{ text: 'OK', onPress: () => router.back() }]
    );
  };

  return (
    <View style={styles.root}>
      <StatusBar barStyle="dark-content" backgroundColor="#FFFFFF" />

      <SafeAreaView edges={['top']} style={styles.safeTop}>
        <View style={styles.header}>
          <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
            <Feather name="arrow-left" size={20} color="#0F172A" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Package Unavailable</Text>
          <View style={{ width: 36 }} />
        </View>
      </SafeAreaView>

      <View style={styles.content}>
        <View style={styles.illustrationCircle}>
          <Feather name="book-open" size={42} color="#0745E8" />
        </View>

        <Text style={styles.title}>Package Currently Under Creation</Text>
        <Text style={styles.description}>
          Passing Package for <Text style={styles.highlight}>{activeBranch} Semester {activeSemester}</Text> is currently being generated by our VTU top-ranker team.
        </Text>

        <View style={styles.bulletBox}>
          <View style={styles.bulletRow}>
            <Feather name="check-circle" size={16} color="#059669" />
            <Text style={styles.bulletText}>Includes 5-Year Repeated VTU Questions</Text>
          </View>
          <View style={styles.bulletRow}>
            <Feather name="check-circle" size={16} color="#059669" />
            <Text style={styles.bulletText}>Unit Weightage & Progress Visualizer</Text>
          </View>
          <View style={styles.bulletRow}>
            <Feather name="check-circle" size={16} color="#059669" />
            <Text style={styles.bulletText}>1-Night-Before Exam Sequence</Text>
          </View>
        </View>

        <TouchableOpacity
          activeOpacity={0.85}
          style={styles.requestBtn}
          onPress={handleRequestPackage}
        >
          <Feather name="send" size={18} color="#FFFFFF" />
          <Text style={styles.requestBtnText}>Notify Me When Package Is Ready</Text>
        </TouchableOpacity>

        <TouchableOpacity
          activeOpacity={0.8}
          style={styles.switchBtn}
          onPress={() => router.push('/passing-packages/select' as any)}
        >
          <Feather name="sliders" size={16} color="#0745E8" />
          <Text style={styles.switchBtnText}>Switch Branch or Semester</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  safeTop: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F172A',
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  illustrationCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 8,
  },
  description: {
    fontSize: 14,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 21,
    marginBottom: 24,
  },
  highlight: {
    color: '#0745E8',
    fontWeight: '700',
  },
  bulletBox: {
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    padding: 16,
    width: '100%',
    marginBottom: 28,
    gap: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bulletText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
  },
  requestBtn: {
    backgroundColor: '#0745E8',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  requestBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  switchBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
  },
  switchBtnText: {
    color: '#0745E8',
    fontSize: 14,
    fontWeight: '700',
  },
});
