import { Subject, Unit, NoteResource } from '../types/notes.types';

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 's1',
    code: '21CS51',
    name: 'Management, Entrepreneurship for IT',
    semester: 5,
    branch: 'CSE',
    unitCount: 5,
    resourceCount: 18,
    progress: 45,
    iconName: 'briefcase',
    iconColor: '#EA580C',
    iconBg: '#FFEDD5',
  },
  {
    id: 's2',
    code: '21CS52',
    name: 'Computer Networks & Security',
    semester: 5,
    branch: 'CSE',
    unitCount: 5,
    resourceCount: 24,
    progress: 75,
    iconName: 'globe',
    iconColor: '#2563EB',
    iconBg: '#DBEAFE',
  },
  {
    id: 's3',
    code: '21CS53',
    name: 'Database Management Systems',
    semester: 5,
    branch: 'CSE',
    unitCount: 5,
    resourceCount: 21,
    progress: 60,
    iconName: 'database',
    iconColor: '#9333EA',
    iconBg: '#F3E8FF',
  },
  {
    id: 's4',
    code: '21CS54',
    name: 'Automata Theory & Computability',
    semester: 5,
    branch: 'CSE',
    unitCount: 5,
    resourceCount: 16,
    progress: 30,
    iconName: 'cpu',
    iconColor: '#16A34A',
    iconBg: '#DCFCE7',
  },
  {
    id: 's5',
    code: '21CSL55',
    name: 'Web Technology Lab',
    semester: 5,
    branch: 'CSE',
    unitCount: 5,
    resourceCount: 12,
    progress: 90,
    iconName: 'code',
    iconColor: '#0284C7',
    iconBg: '#E0F2FE',
  },
];

export const MOCK_UNITS: Unit[] = [
  { id: 'u1', unitNumber: 1, title: 'Introduction & Application Layer (HTTP, DNS, SMTP)', resourceCount: 6, progress: 100 },
  { id: 'u2', unitNumber: 2, title: 'Transport Layer (TCP, UDP, Congestion Control)', resourceCount: 5, progress: 80 },
  { id: 'u3', unitNumber: 3, title: 'Network Layer & IP Addressing (IPv4/v6, Subnetting)', resourceCount: 5, progress: 50 },
  { id: 'u4', unitNumber: 4, title: 'Data Link Layer & MAC Protocols (Ethernet, Switches)', resourceCount: 4, progress: 20 },
  { id: 'u5', unitNumber: 5, title: 'Network Security & Cryptography Basics', resourceCount: 4, progress: 0 },
];

export const MOCK_RESOURCES: NoteResource[] = [
  {
    id: 'r1',
    title: 'Module 1 Complete Lecture Notes (Handwritten)',
    subjectId: 's2',
    subjectName: 'Computer Networks',
    subjectCode: '21CS52',
    unitNumber: 1,
    unitTitle: 'Application Layer',
    type: 'Handwritten Notes',
    fileFormat: 'PDF',
    fileSize: '3.4 MB',
    author: 'Prof. Ramesh K.',
    downloadsCount: 428,
    isBookmarked: true,
    isDownloaded: true,
    description: 'Comprehensive handwritten module notes covering HTTP, DNS, Socket Programming, and P2P Architecture.',
    totalPages: 32,
    isPaid: true,
    price: 29,
    freePreviewPages: 2,
    tableOfContents: [
      '1. Network Edge & Core Architecture',
      '2. HTTP/1.1 vs HTTP/2 Mechanisms',
      '3. Domain Name System (DNS) Resolution',
      '4. Socket Programming in Python/C',
    ],
  },
  {
    id: 'r2',
    title: 'Transport Layer TCP/UDP Revision Short Notes',
    subjectId: 's2',
    subjectName: 'Computer Networks',
    subjectCode: '21CS52',
    unitNumber: 2,
    unitTitle: 'Transport Layer',
    type: 'Short Notes',
    fileFormat: 'PDF',
    fileSize: '1.2 MB',
    author: 'VTU Toppers Club',
    downloadsCount: 890,
    isBookmarked: false,
    isDownloaded: false,
    description: 'Quick exam night revision notes with TCP 3-way handshake diagrams and congestion window formulas.',
    totalPages: 12,
    tableOfContents: [
      '1. TCP Header Structure & Flags',
      '2. 3-Way Handshake & Teardown',
      '3. Sliding Window Protocol & Go-Back-N',
      '4. Congestion Control Algorithms',
    ],
  },
  {
    id: 'r3',
    title: 'IP Subnetting & CIDR Practice Problems (Typed)',
    subjectId: 's2',
    subjectName: 'Computer Networks',
    subjectCode: '21CS52',
    unitNumber: 3,
    unitTitle: 'Network Layer',
    type: 'Typed Notes',
    fileFormat: 'PDF',
    fileSize: '2.1 MB',
    author: 'Dept. of CSE',
    downloadsCount: 310,
    isBookmarked: true,
    isDownloaded: false,
    description: '25 solved numerical problems on VLSM, CIDR notation, and IP address allocation for semester exams.',
    totalPages: 18,
  },
  {
    id: 'r4',
    title: 'DBMS ER Diagrams & Normalization Short Notes',
    subjectId: 's3',
    subjectName: 'Database Management Systems',
    subjectCode: '21CS53',
    unitNumber: 2,
    unitTitle: 'Relational Model & Normalization',
    type: 'Revision Notes',
    fileFormat: 'PDF',
    fileSize: '1.8 MB',
    author: 'Dr. Priya V.',
    downloadsCount: 650,
    isBookmarked: false,
    isDownloaded: true,
    description: 'Step-by-step breakdown of 1NF, 2NF, 3NF, BCNF with VTU past exam solved examples.',
    totalPages: 24,
  },
  {
    id: 'r5',
    title: 'DBMS Module 1 & 2 Complete Handwritten Class Notes',
    subjectId: 's3',
    subjectName: 'Database Management Systems',
    subjectCode: '21CS53',
    unitNumber: 1,
    unitTitle: 'Relational Algebra & SQL',
    type: 'Handwritten Notes',
    fileFormat: 'PDF',
    fileSize: '4.1 MB',
    author: 'VTU Rank Holder (B.E CSE)',
    downloadsCount: 940,
    isBookmarked: true,
    isDownloaded: true,
    description: 'Neatly written class notes with ER diagrams, SQL queries, relational algebra syntax, and solved IA test questions.',
    totalPages: 38,
  },
  {
    id: 'r6',
    title: 'Automata Theory (21CS54) Module 1 & 2 Handwritten Notes',
    subjectId: 's4',
    subjectName: 'Automata Theory & Computability',
    subjectCode: '21CS54',
    unitNumber: 1,
    unitTitle: 'DFA & NFA State Diagrams',
    type: 'Handwritten Notes',
    fileFormat: 'PDF',
    fileSize: '5.2 MB',
    author: 'Prof. Suresh Kumar',
    downloadsCount: 780,
    isBookmarked: false,
    isDownloaded: true,
    description: 'Hand-drawn DFA/NFA state transition diagrams, epsilon transitions, and minimization step-by-step guides.',
    totalPages: 44,
  },
  {
    id: 'r7',
    title: 'Management IT (21CS51) Handwritten Summary Diagrams',
    subjectId: 's1',
    subjectName: 'Management & Entrepreneurship',
    subjectCode: '21CS51',
    unitNumber: 1,
    unitTitle: 'Principles of Management',
    type: 'Handwritten Notes',
    fileFormat: 'PDF',
    fileSize: '2.8 MB',
    author: 'Ananya S.',
    downloadsCount: 350,
    isBookmarked: false,
    isDownloaded: false,
    description: 'Handwritten mind maps and bullet summaries for quick memory retention before VTU exams.',
    totalPages: 16,
  },
];
