import { AcademicEvent, AcademicTimelineStage } from '../types/calendar.types';

export const MOCK_ACADEMIC_EVENTS: AcademicEvent[] = [
  {
    id: 'evt-sem-start',
    title: 'Commencement of 5th Semester Classes',
    category: 'Semester Dates',
    date: '2026-08-10',
    time: '09:00 AM',
    semester: 5,
    branch: 'ALL',
    scheme: '2022',
    description: 'Official commencement of academic instruction for 5th semester B.E. courses under NEP 2022 Scheme.',
    vtuCircularRef: 'VTU/ACA/CIRCULAR/2026/102',
    isImportant: true,
  },
  {
    id: 'evt-ia1',
    title: 'First Internal Assessment (IA-1)',
    category: 'Internals',
    date: '2026-09-16',
    time: '09:30 AM - 11:00 AM',
    semester: 5,
    branch: 'CSE',
    scheme: '2022',
    venue: 'Department Exam Block (Halls 201-205)',
    description: 'First internal test covering Module 1 & Module 2 topics for 5th semester Computer Science & Engg.',
    vtuCircularRef: 'VTU/EXAM/IA/2026/412',
    isImportant: true,
  },
  {
    id: 'evt-gh-rajyotsava',
    title: 'Kannada Rajyotsava (General Holiday)',
    category: 'Holidays',
    date: '2026-11-01',
    semester: 5,
    branch: 'ALL',
    scheme: 'ALL',
    description: 'Declared State Holiday on account of Kannada Rajyotsava celebration across all VTU affiliated colleges.',
    isImportant: false,
  },
  {
    id: 'evt-ia2',
    title: 'Second Internal Assessment (IA-2)',
    category: 'Internals',
    date: '2026-10-14',
    time: '09:30 AM - 11:00 AM',
    semester: 5,
    branch: 'CSE',
    scheme: '2022',
    venue: 'Department Exam Block',
    description: 'Second internal assessment covering Module 3 & Module 4 syllabus.',
    vtuCircularRef: 'VTU/EXAM/IA/2026/518',
    isImportant: true,
  },
  {
    id: 'evt-lab-exam',
    title: 'VTU Semester Practical & Lab Examinations',
    category: 'Lab Exams',
    date: '2026-11-20',
    time: '08:30 AM - 04:30 PM',
    semester: 5,
    branch: 'CSE',
    scheme: '2022',
    venue: 'CN & DBMS Computer Laboratories',
    description: 'Practical examinations and viva-voce for Computer Networks (21CSL57) and DBMS Lab (21CSL58).',
    vtuCircularRef: 'VTU/EXAM/LAB/2026/720',
    isImportant: true,
  },
  {
    id: 'evt-see-exam',
    title: 'VTU Semester End Examinations (SEE Theory)',
    category: 'Exams',
    date: '2026-12-05',
    time: '02:00 PM - 05:00 PM',
    semester: 5,
    branch: 'ALL',
    scheme: '2022',
    venue: 'Main Campus Examination Center',
    description: 'Final Semester End Examination for 5th Semester B.E. theory subjects.',
    vtuCircularRef: 'VTU/EXAM/SEE/2026/905',
    isImportant: true,
  },
  {
    id: 'evt-result',
    title: 'Announcement of 5th Sem SEE Results',
    category: 'Results',
    date: '2027-01-20',
    time: '06:00 PM',
    semester: 5,
    branch: 'ALL',
    scheme: '2022',
    description: 'Official declaration of 5th Semester B.E. results on VTU Official Results Portal.',
    vtuCircularRef: 'VTU/RESULT/2027/012',
    isImportant: true,
  },
];

export const MOCK_TIMELINE_STAGES: AcademicTimelineStage[] = [
  {
    id: 'stg-commence',
    stageName: 'Semester Commencement',
    dateRange: 'Aug 10, 2026',
    status: 'COMPLETED',
    description: 'Classes begin & syllabus orientation',
  },
  {
    id: 'stg-ia1',
    stageName: '1st Internal Assessment',
    dateRange: 'Sep 16 - Sep 19, 2026',
    status: 'IN_PROGRESS',
    description: 'Assessment of Modules 1 & 2',
  },
  {
    id: 'stg-ia2',
    stageName: '2nd Internal Assessment',
    dateRange: 'Oct 14 - Oct 17, 2026',
    status: 'UPCOMING',
    description: 'Assessment of Modules 3 & 4',
  },
  {
    id: 'stg-lab',
    stageName: 'Lab Exams & Viva',
    dateRange: 'Nov 20 - Nov 28, 2026',
    status: 'UPCOMING',
    description: 'Practical examination & lab evaluation',
  },
  {
    id: 'stg-see',
    stageName: 'SEE Theory Exams',
    dateRange: 'Dec 05 - Dec 24, 2026',
    status: 'UPCOMING',
    description: 'Semester End University Examinations',
  },
];
