import { PassingPackage } from '../types/passingPackages.types';

export const MOCK_PASSING_PACKAGES: PassingPackage[] = [
  {
    id: 'pp-cn-21cs52',
    subjectCode: '21CS52',
    subjectName: 'Computer Networks & Security',
    semester: 5,
    branch: 'CSE',
    scheme: '2022',
    unitCount: 5,
    totalQuestionsCount: 42,
    importantQuestionsCount: 18,
    repeatedQuestionsCount: 12,
    expectedQuestionsCount: 12,
    revisionResourceCount: 8,
    unitsWeightage: [
      {
        unitNumber: 1,
        unitTitle: 'Application Layer & HTTP/DNS Protocols',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'Must Master',
        questionsCount: 9,
        revisionResourceCount: 2,
        summary: 'Focus on OSI vs TCP/IP model, HTTP persistent connection timing diagrams, and DNS resolution hierarchy.',
      },
      {
        unitNumber: 2,
        unitTitle: 'Transport Layer (TCP/UDP & Congestion)',
        expectedMarks: 22,
        percentageWeightage: 22,
        importanceLevel: 'Must Master',
        questionsCount: 10,
        revisionResourceCount: 2,
        summary: 'TCP 3-way handshake diagrams, Go-Back-N vs Selective Repeat ARQ numericals, and Congestion Control window graphs.',
      },
      {
        unitNumber: 3,
        unitTitle: 'Network Layer & IP Addressing',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'Must Master',
        questionsCount: 8,
        revisionResourceCount: 2,
        summary: 'Dijkstra shortest path algorithm, Distance Vector routing, IPv4 header fragmentation fields, and CIDR subnetting.',
      },
      {
        unitNumber: 4,
        unitTitle: 'Data Link Layer & MAC Protocols',
        expectedMarks: 18,
        percentageWeightage: 18,
        importanceLevel: 'High Weightage',
        questionsCount: 8,
        revisionResourceCount: 1,
        summary: 'CSMA/CD flowchart, 16-bit CRC checksum calculation, and Ethernet frame structure.',
      },
      {
        unitNumber: 5,
        unitTitle: 'Network Security & Cryptography Basics',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'High Weightage',
        questionsCount: 7,
        revisionResourceCount: 1,
        summary: 'RSA public-key encryption numericals, Firewalls, SSL/TLS handshake, and AES key generation.',
      },
    ],
    importantQuestions: [
      {
        id: 'iq-cn-1',
        questionText: 'Draw and explain OSI Reference Model with neat block diagrams. Detail exact functions of each layer.',
        unitNumber: 1,
        unitTitle: 'Application Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg', '2022 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L2',
        relatedNoteId: 'r1',
        relatedPaperId: 'pyq-cn-2024-reg',
        solutionSnippet: 'Physical, Data Link, Network, Transport, Session, Presentation, Application. Explain encapsulation and PDU at each layer.',
        diagramAvailable: true,
        diagramTitle: '7-Layer OSI Stack Encapsulation Diagram',
        keyPoints: [
          'Diagram showing 7 layers with directional arrows',
          'Explain Data Link (Framing, MAC) and Network (IP Routing)',
          'Highlight Transport Layer end-to-end reliability (TCP/UDP)',
          'Mention Application Layer protocols: HTTP, SMTP, DNS',
        ],
      },
      {
        id: 'iq-cn-2',
        questionText: 'Explain TCP 3-way handshake mechanism for connection establishment and teardown with sequence diagrams.',
        unitNumber: 2,
        unitTitle: 'Transport Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Model', '2022 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        relatedNoteId: 'r2',
        relatedPaperId: 'pyq-cn-2024-reg',
        solutionSnippet: 'SYN (seq=x), SYN-ACK (seq=y, ack=x+1), ACK (ack=y+1). Teardown uses FIN, ACK, FIN, ACK sequence.',
        diagramAvailable: true,
        diagramTitle: 'TCP Handshake Timeline Diagram',
        keyPoints: [
          'Client -> Server SYN with initial sequence number',
          'Server -> Client SYN+ACK acknowledgment',
          'Client -> Server final ACK transition to ESTABLISHED state',
          '4-step termination using FIN and TIME-WAIT states',
        ],
      },
      {
        id: 'iq-cn-3',
        questionText: 'Apply Dijkstra shortest path algorithm for a given 6-node network graph. Show step-by-step distance table updates.',
        unitNumber: 3,
        unitTitle: 'Network Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg', '2021 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        relatedNoteId: 'r3',
        relatedPaperId: 'pyq-cn-2024-reg',
        solutionSnippet: 'Set source node d(u)=0, all others infinity. Iteratively select min-distance unvisited node and update neighbor distances.',
        diagramAvailable: true,
        diagramTitle: 'Graph Topology & Stepwise Distance Table',
        keyPoints: [
          'Initialization step with set N\' = {u}',
          'Tabular column showing iterations k = 1 to 5',
          'Distance formula: D(v) = min(D(v), D(w) + c(w,v))',
          'Final shortest paths tree output',
        ],
      },
      {
        id: 'iq-cn-4',
        questionText: 'Compute 16-bit CRC checksum for data block D = 1101011011 using generator polynomial G = 10011.',
        unitNumber: 4,
        unitTitle: 'Data Link Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2022 Reg'],
        priority: 'High Priority',
        bloomLevel: 'L3',
        relatedPaperId: 'pyq-cn-2024-reg',
        solutionSnippet: 'Append r=4 zeros to D -> 11010110110000. Perform modulo-2 binary division by G (10011). Remainder is CRC checksum.',
        diagramAvailable: false,
        keyPoints: [
          'Degree of generator polynomial r = 4',
          'Append r zeros to original frame',
          'XOR operations step-by-step for modulo-2 division',
          'Final transmitted frame = D + Remainder',
        ],
      },
      {
        id: 'iq-cn-5',
        questionText: 'Explain RSA public key encryption algorithm with a numerical example (Take p=3, q=11, e=7, M=5).',
        unitNumber: 5,
        unitTitle: 'Network Security',
        marks: 10,
        sourceYears: ['2023 Reg', '2022 Reg'],
        priority: 'High Priority',
        bloomLevel: 'L3',
        solutionSnippet: 'n = p*q = 33, phi(n) = (p-1)*(q-1) = 20. d*e mod phi(n) = 1 => d = 3. C = M^e mod n = 5^7 mod 33 = 14.',
        diagramAvailable: false,
        keyPoints: [
          'Calculate n = p*q and Euler totient phi(n)',
          'Choose public exponent e coprime to phi(n)',
          'Compute private exponent d using extended Euclidean algorithm',
          'Ciphertext C = M^e mod n and Decrypted Message M = C^d mod n',
        ],
      },
    ],
    repeatedQuestions: [
      {
        id: 'rq-cn-1',
        questionText: 'Distinguish between HTTP persistent vs non-persistent connections with suitable timing diagrams.',
        unitNumber: 1,
        unitTitle: 'Application Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg', '2022 Reg', '2021 Reg'],
        frequency: '4x in Last 5 Years',
        priority: 'Very High Priority',
        bloomLevel: 'L2',
        relatedNoteId: 'r1',
        relatedPaperId: 'pyq-cn-2024-reg',
        solutionSnippet: 'Non-persistent: 2 RTTs per object (1 for TCP connection + 1 for request/response). Persistent: 1 RTT for TCP, multiple objects sent.',
        diagramAvailable: true,
        diagramTitle: 'RTT Timing Comparison Chart',
      },
      {
        id: 'rq-cn-2',
        questionText: 'Explain TCP Congestion Control algorithms: Slow Start, Congestion Avoidance, and Fast Recovery.',
        unitNumber: 2,
        unitTitle: 'Transport Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg', '2022 Reg'],
        frequency: '3x in Last 5 Years',
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        relatedNoteId: 'r2',
        relatedPaperId: 'pyq-cn-2024-reg',
        solutionSnippet: 'cwnd doubles every RTT during Slow Start until ssthresh. cwnd grows linearly (+1 MSS per RTT) during Congestion Avoidance.',
        diagramAvailable: true,
        diagramTitle: 'cwnd vs Time Transmission Curve',
      },
      {
        id: 'rq-cn-3',
        questionText: 'Explain IPv4 header format with a neat diagram and detail the fields used for IP fragmentation.',
        unitNumber: 3,
        unitTitle: 'Network Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg', '2021 Makeup'],
        frequency: '3x in Last 5 Years',
        priority: 'High Priority',
        bloomLevel: 'L2',
        relatedPaperId: 'pyq-cn-2024-reg',
        diagramAvailable: true,
        diagramTitle: '32-Bit IPv4 Header Structure',
      },
      {
        id: 'rq-cn-4',
        questionText: 'Explain CSMA/CD mechanism used in Ethernet networks with a neat flowchart.',
        unitNumber: 4,
        unitTitle: 'Data Link Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2022 Reg', '2020 Reg'],
        frequency: '3x in Last 5 Years',
        priority: 'High Priority',
        bloomLevel: 'L2',
        relatedPaperId: 'pyq-cn-2024-reg',
        diagramAvailable: true,
        diagramTitle: 'CSMA/CD Flowchart Diagram',
      },
    ],
    expectedQuestions: [
      {
        id: 'eq-cn-1',
        questionText: 'Differentiate between Distance Vector Routing and Link State Routing protocols with examples.',
        unitNumber: 3,
        unitTitle: 'Network Layer',
        marks: 10,
        sourceYears: ['2023 Model', '2022 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L2',
      },
      {
        id: 'eq-cn-2',
        questionText: 'Explain Domain Name System (DNS) recursive vs iterative query resolution with sequence diagrams.',
        unitNumber: 1,
        unitTitle: 'Application Layer',
        marks: 10,
        sourceYears: ['2023 Reg', '2021 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L2',
      },
      {
        id: 'eq-cn-3',
        questionText: 'Differentiate between Go-Back-N ARQ and Selective Repeat ARQ sliding window protocols.',
        unitNumber: 2,
        unitTitle: 'Transport Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2022 Reg'],
        priority: 'High Priority',
        bloomLevel: 'L2',
      },
      {
        id: 'eq-cn-4',
        questionText: 'Explain SSL/TLS handshaking architecture and record protocol for secure web browsing.',
        unitNumber: 5,
        unitTitle: 'Network Security',
        marks: 10,
        sourceYears: ['2023 Model'],
        priority: 'Medium Priority',
        bloomLevel: 'L2',
      },
    ],
    revisionResources: [
      {
        id: 'rr-cn-pdf1',
        title: 'CN Unit 1-5 Last Minute Formula & Diagram Cheat-Sheet',
        subTitle: 'Contains 15 vital VTU diagrams, TCP formulas & subnetting tables',
        type: 'Quick PDF',
        fileSize: '1.8 MB',
        pageCount: 8,
        unitNumber: 1,
        isDownloaded: true,
        isBookmarked: true,
        previewSnippet: 'Handy 8-page summary containing OSI vs TCP/IP, TCP 3-Way Handshake, IPv4 Header, and Dijkstra flowchart.',
      },
      {
        id: 'rr-cn-pdf2',
        title: '1-Night-Before Exam High-Yield Summary Notes',
        subTitle: 'Condensed bullet notes covering 80% of VTU repeat questions',
        type: 'Key Concepts',
        fileSize: '2.4 MB',
        pageCount: 14,
        unitNumber: 2,
        isDownloaded: false,
        isBookmarked: true,
        previewSnippet: 'Condensed exam night notes curated by VTU top rankers for rapid memory recall.',
      },
      {
        id: 'rr-cn-pdf3',
        title: 'Computer Networks Important Diagrams & Flowcharts',
        subTitle: 'High resolution clean diagrams ready to draw in answer sheet',
        type: 'Important Diagrams',
        fileSize: '3.1 MB',
        pageCount: 10,
        unitNumber: 3,
        isDownloaded: false,
        isBookmarked: false,
        previewSnippet: 'Visual collection of all 15 compulsory diagrams required for 10-mark VTU answers.',
      },
      {
        id: 'rr-cn-pdf4',
        title: 'IP Subnetting & CRC Checksum Solved Numericals Sheet',
        subTitle: '12 solved problems from previous 5 years VTU papers',
        type: 'Formula Sheet',
        fileSize: '1.2 MB',
        pageCount: 6,
        unitNumber: 4,
        isDownloaded: true,
        isBookmarked: false,
        previewSnippet: 'Step-by-step solved numericals for guaranteed 10 marks in Unit 3 & Unit 4.',
      },
    ],
    nightBeforeSequence: [
      {
        id: 'iq-cn-1',
        questionText: 'Draw and explain OSI Reference Model with neat block diagrams. Detail exact functions of each layer.',
        unitNumber: 1,
        unitTitle: 'Application Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L2',
        solutionSnippet: 'Physical, Data Link, Network, Transport, Session, Presentation, Application. Diagram carries 4 marks.',
        diagramAvailable: true,
        diagramTitle: 'OSI 7-Layer Architecture',
      },
      {
        id: 'iq-cn-2',
        questionText: 'Explain TCP 3-way handshake mechanism for connection establishment and teardown.',
        unitNumber: 2,
        unitTitle: 'Transport Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Model'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        solutionSnippet: 'SYN, SYN-ACK, ACK timeline diagram. Must write SYN sequence number generation.',
        diagramAvailable: true,
        diagramTitle: 'TCP Handshake Timeline',
      },
      {
        id: 'iq-cn-3',
        questionText: 'Apply Dijkstra shortest path algorithm for a given 6-node network graph.',
        unitNumber: 3,
        unitTitle: 'Network Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2021 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        solutionSnippet: 'Draw network topology, initialize distance array, update step-by-step in table.',
        diagramAvailable: true,
        diagramTitle: 'Dijkstra Step Table',
      },
      {
        id: 'rq-cn-1',
        questionText: 'Distinguish between HTTP persistent vs non-persistent connections with timing diagrams.',
        unitNumber: 1,
        unitTitle: 'Application Layer',
        marks: 10,
        sourceYears: ['2024 Reg', '2023 Reg'],
        frequency: '4x in Last 5 Years',
        priority: 'Very High Priority',
        bloomLevel: 'L2',
        diagramAvailable: true,
        diagramTitle: 'RTT Timing Comparison',
      },
    ],
  },

  {
    id: 'pp-dbms-21cs53',
    subjectCode: '21CS53',
    subjectName: 'Database Management Systems',
    semester: 5,
    branch: 'CSE',
    scheme: '2022',
    unitCount: 5,
    totalQuestionsCount: 38,
    importantQuestionsCount: 16,
    repeatedQuestionsCount: 10,
    expectedQuestionsCount: 10,
    revisionResourceCount: 6,
    unitsWeightage: [
      {
        unitNumber: 1,
        unitTitle: 'ER Modeling & Relational Algebra',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'Must Master',
        questionsCount: 8,
        revisionResourceCount: 1,
        summary: 'ER diagram design for Hospital/Library/Company DB, Relational algebra operators (Select, Project, Join).',
      },
      {
        unitNumber: 2,
        unitTitle: 'SQL Queries & Subqueries',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'Must Master',
        questionsCount: 8,
        revisionResourceCount: 2,
        summary: 'Nested queries, GROUP BY, HAVING, INNER/OUTER JOINs, and DDL/DML syntax.',
      },
      {
        unitNumber: 3,
        unitTitle: 'Database Normalization (1NF to BCNF)',
        expectedMarks: 22,
        percentageWeightage: 22,
        importanceLevel: 'Must Master',
        questionsCount: 9,
        revisionResourceCount: 1,
        summary: 'Functional dependency closure, 1NF, 2NF, 3NF, BCNF step-by-step conversion examples.',
      },
      {
        unitNumber: 4,
        unitTitle: 'Transaction Processing & Concurrency Control',
        expectedMarks: 18,
        percentageWeightage: 18,
        importanceLevel: 'High Weightage',
        questionsCount: 7,
        revisionResourceCount: 1,
        summary: 'ACID properties, 2-Phase Locking (2PL), Serializability, and Deadlock handling.',
      },
      {
        unitNumber: 5,
        unitTitle: 'Indexing & NoSQL Databases',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'High Weightage',
        questionsCount: 6,
        revisionResourceCount: 1,
        summary: 'B+ Tree indexing insertion, Hashing, MongoDB Document schema, and CAP Theorem.',
      },
    ],
    importantQuestions: [
      {
        id: 'iq-db-1',
        questionText: 'Design an ER diagram for a Hospital Management System. Define entity sets, primary keys, and cardinalities.',
        unitNumber: 1,
        unitTitle: 'ER Modeling',
        marks: 10,
        sourceYears: ['2023 Reg', '2022 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        relatedNoteId: 'r4',
        relatedPaperId: 'pyq-dbms-2023-reg',
        solutionSnippet: 'Entities: Doctor, Patient, Ward, Treatment. Draw rectangles, ovals for attributes, diamonds for relationships.',
        diagramAvailable: true,
        diagramTitle: 'Hospital ER Diagram',
      },
      {
        id: 'iq-db-2',
        questionText: 'Define 1NF, 2NF, 3NF, and BCNF with suitable relational schema examples.',
        unitNumber: 3,
        unitTitle: 'Normalization',
        marks: 12,
        sourceYears: ['2023 Reg', '2021 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        relatedNoteId: 'r4',
        relatedPaperId: 'pyq-dbms-2023-reg',
        solutionSnippet: '1NF: Atomic values. 2NF: No partial dependency. 3NF: No transitive dependency. BCNF: X in X->A is superkey.',
        diagramAvailable: false,
      },
    ],
    repeatedQuestions: [
      {
        id: 'rq-db-1',
        questionText: 'Explain ACID properties of a transaction with suitable banking application examples.',
        unitNumber: 4,
        unitTitle: 'Transaction Processing',
        marks: 10,
        sourceYears: ['2023 Reg', '2022 Reg', '2021 Reg'],
        frequency: '3x in Last 5 Years',
        priority: 'Very High Priority',
        bloomLevel: 'L2',
        diagramAvailable: false,
      },
    ],
    expectedQuestions: [
      {
        id: 'eq-db-1',
        questionText: 'Construct a B+ Tree of order 3 for inserting keys: 10, 20, 30, 40, 50, 60, 70.',
        unitNumber: 5,
        unitTitle: 'Indexing',
        marks: 10,
        sourceYears: ['2023 Model'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
      },
    ],
    revisionResources: [
      {
        id: 'rr-db-pdf1',
        title: 'DBMS Normalization & ER Diagrams Solved Guide',
        subTitle: 'Includes step-by-step BCNF proofs and ER notation symbols',
        type: 'Quick PDF',
        fileSize: '2.1 MB',
        pageCount: 12,
        unitNumber: 3,
        isDownloaded: true,
        isBookmarked: false,
      },
    ],
    nightBeforeSequence: [
      {
        id: 'iq-db-2',
        questionText: 'Define 1NF, 2NF, 3NF, and BCNF with suitable relational schema examples.',
        unitNumber: 3,
        unitTitle: 'Normalization',
        marks: 12,
        sourceYears: ['2023 Reg', '2021 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
      },
    ],
  },

  {
    id: 'pp-atc-21cs54',
    subjectCode: '21CS54',
    subjectName: 'Automata Theory & Computability',
    semester: 5,
    branch: 'CSE',
    scheme: '2022',
    unitCount: 5,
    totalQuestionsCount: 35,
    importantQuestionsCount: 14,
    repeatedQuestionsCount: 8,
    expectedQuestionsCount: 9,
    revisionResourceCount: 5,
    unitsWeightage: [
      {
        unitNumber: 1,
        unitTitle: 'Deterministic & Non-Deterministic Finite Automata (DFA/NFA)',
        expectedMarks: 22,
        percentageWeightage: 22,
        importanceLevel: 'Must Master',
        questionsCount: 8,
        revisionResourceCount: 2,
        summary: 'DFA construction for binary numbers, NFA to DFA conversion, and Epsilon-closure algorithms.',
      },
      {
        unitNumber: 2,
        unitTitle: 'Regular Expressions & Regular Languages',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'Must Master',
        questionsCount: 7,
        revisionResourceCount: 1,
        summary: 'Pumping Lemma for Regular Languages, Arden Theorem, and State Minimization.',
      },
      {
        unitNumber: 3,
        unitTitle: 'Context Free Grammars (CFG) & Pushdown Automata (PDA)',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'Must Master',
        questionsCount: 7,
        revisionResourceCount: 1,
        summary: 'Derivation trees, Ambiguity in CFG, Chomsky Normal Form (CNF), and PDA design.',
      },
      {
        unitNumber: 4,
        unitTitle: 'Turing Machines (TM) & Decidability',
        expectedMarks: 18,
        percentageWeightage: 18,
        importanceLevel: 'High Weightage',
        questionsCount: 7,
        revisionResourceCount: 1,
        summary: 'Turing Machine design for a^n b^n c^n, Halting Problem proof, and Post Correspondence Problem.',
      },
      {
        unitNumber: 5,
        unitTitle: 'Complexity Theory (P, NP & NP-Complete)',
        expectedMarks: 20,
        percentageWeightage: 20,
        importanceLevel: 'High Weightage',
        questionsCount: 6,
        revisionResourceCount: 0,
        summary: 'P vs NP classes, Satisfiability problem (3-SAT), and Polynomial time reductions.',
      },
    ],
    importantQuestions: [
      {
        id: 'iq-atc-1',
        questionText: 'Construct a DFA that accepts binary numbers divisible by 3. Show state transition table and state diagram.',
        unitNumber: 1,
        unitTitle: 'Finite Automata',
        marks: 10,
        sourceYears: ['2023 Model', '2022 Reg'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
        relatedPaperId: 'pyq-atc-2023-model',
        diagramAvailable: true,
        diagramTitle: '3-State DFA Transition Diagram',
      },
    ],
    repeatedQuestions: [
      {
        id: 'rq-atc-1',
        questionText: 'State and prove Pumping Lemma for Regular Languages. Show that L = {a^n b^n | n >= 0} is not regular.',
        unitNumber: 2,
        unitTitle: 'Regular Languages',
        marks: 10,
        sourceYears: ['2023 Reg', '2022 Reg', '2021 Reg'],
        frequency: '3x in Last 5 Years',
        priority: 'Very High Priority',
        bloomLevel: 'L3',
      },
    ],
    expectedQuestions: [
      {
        id: 'eq-atc-1',
        questionText: 'Design a Pushdown Automata (PDA) for accepting language L = { w w^R | w in {a,b}* } by empty stack.',
        unitNumber: 3,
        unitTitle: 'PDA',
        marks: 10,
        sourceYears: ['2023 Model'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
      },
    ],
    revisionResources: [
      {
        id: 'rr-atc-pdf1',
        title: 'ATC DFA/NFA Transition Diagrams Cheat Sheet',
        subTitle: '20 clean hand-drawn state diagrams for semester exams',
        type: 'Important Diagrams',
        fileSize: '3.5 MB',
        pageCount: 10,
        unitNumber: 1,
        isDownloaded: false,
        isBookmarked: true,
      },
    ],
    nightBeforeSequence: [
      {
        id: 'iq-atc-1',
        questionText: 'Construct a DFA that accepts binary numbers divisible by 3. Show transition table.',
        unitNumber: 1,
        unitTitle: 'Finite Automata',
        marks: 10,
        sourceYears: ['2023 Model'],
        priority: 'Very High Priority',
        bloomLevel: 'L3',
      },
    ],
  },
];

export const BRANCH_LIST = [
  { code: 'CSE', name: 'Computer Science & Engineering' },
  { code: 'ISE', name: 'Information Science & Engineering' },
  { code: 'ECE', name: 'Electronics & Communication Engg' },
  { code: 'EEE', name: 'Electrical & Electronics Engg' },
  { code: 'ME', name: 'Mechanical Engineering' },
  { code: 'CIV', name: 'Civil Engineering' },
];

export const SEMESTER_LIST = [1, 2, 3, 4, 5, 6, 7, 8];

export const SCHEME_LIST = ['2022 Scheme (NEP)', '2021 Scheme (NEP)', '2018 Scheme (CBCS)'];
