import { CommunityResource, Contributor } from '../types/community.types';

export const MOCK_CONTRIBUTORS: Contributor[] = [
  {
    id: 'c1',
    name: 'Ananya Sharma',
    college: 'Sai Vidya Institute of Technology',
    branch: 'CSE',
    semester: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    contributionsCount: 14,
    totalUpvotes: 840,
    reputationBadge: 'VTU Top Contributor',
  },
  {
    id: 'c2',
    name: 'Rohan Deshmukh',
    college: 'BMS College of Engineering',
    branch: 'CSE',
    semester: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    contributionsCount: 9,
    totalUpvotes: 520,
    reputationBadge: 'Star Scholar',
  },
  {
    id: 'c3',
    name: 'Kavya Ramesh',
    college: 'RV College of Engineering',
    branch: 'ISE',
    semester: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    contributionsCount: 7,
    totalUpvotes: 390,
    reputationBadge: 'Verified Peer',
  },
  {
    id: 'c4',
    name: 'Fardeen Khan',
    college: 'Sai Vidya Institute of Technology',
    branch: 'CSE',
    semester: 5,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    contributionsCount: 5,
    totalUpvotes: 280,
    reputationBadge: 'Star Scholar',
  },
];

export const MOCK_COMMUNITY_RESOURCES: CommunityResource[] = [
  {
    id: 'cr-cn-1',
    title: 'Computer Networks Module 1 & 2 Complete Handwritten Class Notes',
    subjectCode: '21CS52',
    subjectName: 'Computer Networks & Security',
    branch: 'CSE',
    semester: 5,
    scheme: '2022',
    unitNumber: 1,
    resourceType: 'Handwritten Notes',
    fileSize: '4.2 MB',
    fileFormat: 'PDF',
    pageCount: 28,
    contributor: MOCK_CONTRIBUTORS[0],
    rating: 4.9,
    ratingCount: 128,
    usefulCount: 342,
    downloadsCount: 1240,
    viewsCount: 2890,
    isOfficial: false,
    isVerified: true,
    uploadStatus: 'published',
    uploadedAt: '2 days ago',
    description: 'Neat handwritten lecture notes covering OSI model, TCP 3-way handshake, and socket programming with highlighted exam questions.',
    tags: ['Handwritten', 'OSI Model', 'TCP/IP', 'VTU2022Scheme'],
    previewPages: ['Page 1: OSI 7-Layer Diagram', 'Page 2: Socket Functions', 'Page 3: HTTP Protocol'],
  },
  {
    id: 'cr-dbms-1',
    title: 'DBMS Normalization & ER Diagrams Solved Question Bank (2018-2024)',
    subjectCode: '21CS53',
    subjectName: 'Database Management Systems',
    branch: 'CSE',
    semester: 5,
    scheme: '2022',
    unitNumber: 3,
    resourceType: 'Solved Question Bank',
    fileSize: '3.1 MB',
    fileFormat: 'PDF',
    pageCount: 22,
    contributor: MOCK_CONTRIBUTORS[1],
    rating: 4.8,
    ratingCount: 96,
    usefulCount: 280,
    downloadsCount: 980,
    viewsCount: 2150,
    isOfficial: false,
    isVerified: true,
    uploadStatus: 'published',
    uploadedAt: '3 days ago',
    description: 'Step-by-step 1NF, 2NF, 3NF, BCNF proofs and Hospital ER Diagram solved examples from VTU past papers.',
    tags: ['DBMS', 'Normalization', 'ER Diagrams', 'Solved Answers'],
  },
  {
    id: 'cr-atc-1',
    title: 'Automata Theory (ATC) DFA/NFA Transition Diagrams Cheat Sheet',
    subjectCode: '21CS54',
    subjectName: 'Automata Theory & Computability',
    branch: 'CSE',
    semester: 5,
    scheme: '2022',
    unitNumber: 1,
    resourceType: 'Formula Sheet',
    fileSize: '2.5 MB',
    fileFormat: 'PDF',
    pageCount: 12,
    contributor: MOCK_CONTRIBUTORS[2],
    rating: 4.7,
    ratingCount: 74,
    usefulCount: 210,
    downloadsCount: 750,
    viewsCount: 1680,
    isOfficial: false,
    isVerified: true,
    uploadStatus: 'published',
    uploadedAt: '5 days ago',
    description: 'Clean hand-drawn state diagrams for binary divisibility, epsilon transitions, and state minimization rules.',
    tags: ['ATC', 'DFA', 'NFA', 'State Diagrams'],
  },
  {
    id: 'cr-cn-2',
    title: 'CN Unit 3 IP Subnetting & Dijkstra Algorithm Solved Practice Problems',
    subjectCode: '21CS52',
    subjectName: 'Computer Networks & Security',
    branch: 'CSE',
    semester: 5,
    scheme: '2022',
    unitNumber: 3,
    resourceType: 'Typed PDF',
    fileSize: '1.9 MB',
    fileFormat: 'PDF',
    pageCount: 16,
    contributor: MOCK_CONTRIBUTORS[3],
    rating: 4.9,
    ratingCount: 62,
    usefulCount: 185,
    downloadsCount: 620,
    viewsCount: 1420,
    isOfficial: false,
    isVerified: true,
    uploadStatus: 'published',
    uploadedAt: '1 week ago',
    description: '20 numerical problems on CIDR notation, VLSM subnet mask calculation, and 6-node Dijkstra distance tables.',
    tags: ['Subnetting', 'Dijkstra', 'CIDR', 'Numericals'],
  },
  {
    id: 'cr-me-1',
    title: 'Management & Entrepreneurship Unit 1-5 Mindmaps & Flowcharts',
    subjectCode: '21CS51',
    subjectName: 'Management, Entrepreneurship for IT',
    branch: 'CSE',
    semester: 5,
    scheme: '2022',
    unitNumber: 1,
    resourceType: 'Revision Mindmap',
    fileSize: '3.8 MB',
    fileFormat: 'PDF',
    pageCount: 14,
    contributor: MOCK_CONTRIBUTORS[0],
    rating: 4.6,
    ratingCount: 45,
    usefulCount: 140,
    downloadsCount: 480,
    viewsCount: 990,
    isOfficial: false,
    isVerified: false,
    uploadStatus: 'published',
    uploadedAt: '1 week ago',
    description: 'Visual mindmaps for Fayol principles of management, project life cycle, and ERP implementation phases.',
    tags: ['Management', 'Entrepreneurship', 'Mindmaps'],
  },
];
