import { VTUNotification } from '../types/notifications.types';

export const MOCK_NOTIFICATIONS: VTUNotification[] = [
  {
    id: 'notif-ia1-reminder',
    title: 'First Internal Assessment (IA-1) Starts Soon',
    shortMessage: 'IA-1 exams for 5th Sem CSE start on September 16, 2026.',
    fullMessage: 'Reminder: The First Internal Assessment (IA-1) for 5th Semester Computer Science & Engineering commences on Sept 16, 2026. Make sure to review Modules 1 & 2 across Computer Networks and DBMS.',
    category: 'Exams',
    priority: 'High',
    timestamp: '2 hours ago',
    date: '2026-09-03',
    isRead: false,
    targetRoute: '/calendar',
    targetLabel: 'View Exam Schedule in Calendar',
    relatedContext: {
      subjectCode: '21CS51 / 21CS52',
      semester: 5,
      circularRef: 'VTU/EXAM/IA/2026/412',
    },
  },
  {
    id: 'notif-notes-added',
    title: 'New Notes Uploaded: Computer Networks (21CS51)',
    shortMessage: 'Module 3 & Module 4 PDF notes are now available in Notes Library.',
    fullMessage: 'Comprehensive VTU 2022 Scheme notes for Computer Networks (21CS51) Module 3 (Data Link Layer & MAC) and Module 4 (Network Layer) have been added by top VTU faculty.',
    category: 'Study',
    priority: 'Normal',
    timestamp: '5 hours ago',
    date: '2026-09-03',
    isRead: false,
    targetRoute: '/(tabs)/library',
    targetLabel: 'Open Notes Library',
    relatedContext: {
      subjectCode: '21CS51',
      semester: 5,
    },
  },
  {
    id: 'notif-results-declared',
    title: 'VTU 4th Sem Revaluation Results Declared',
    shortMessage: 'Revaluation results for July 2026 exams published on official portal.',
    fullMessage: 'The Visvesvaraya Technological University (VTU) has officially announced the Revaluation Results for 4th Semester B.E. examinations held in June/July 2026.',
    category: 'Results',
    priority: 'High',
    timestamp: '1 day ago',
    date: '2026-09-02',
    isRead: true,
    targetRoute: '/calendar',
    targetLabel: 'View Results Announcement',
    relatedContext: {
      semester: 4,
      circularRef: 'VTU/RESULT/REV/2026/89',
    },
  },
  {
    id: 'notif-pyq-added',
    title: '2025 Jan/Feb Solved Question Papers Added',
    shortMessage: 'Previous year question papers with answer keys updated for 2022 scheme.',
    fullMessage: 'Added 5 previous year question papers (2023 - 2025) with detailed VTU scheme answer keys for Software Engineering and System Software.',
    category: 'Study',
    priority: 'Normal',
    timestamp: '2 days ago',
    date: '2026-09-01',
    isRead: true,
    targetRoute: '/papers',
    targetLabel: 'Browse Solved Question Papers',
    relatedContext: {
      semester: 5,
    },
  },
  {
    id: 'notif-calendar-update',
    title: 'Revised Academic Calendar for 2026-27',
    shortMessage: 'VTU issued updated notification regarding SEE practical exam dates.',
    fullMessage: 'Official Circular: Revised schedule for 5th & 7th Semester Practical Examinations and Commencement of Even Semesters for academic year 2026-27.',
    category: 'Academic',
    priority: 'Normal',
    timestamp: '3 days ago',
    date: '2026-08-31',
    isRead: true,
    targetRoute: '/calendar',
    targetLabel: 'Check Updated Calendar',
    relatedContext: {
      circularRef: 'VTU/ACA/CAL/2026/650',
    },
  },
  {
    id: 'notif-app-feature',
    title: 'VTU Super App v1.2 Upgrade Released',
    shortMessage: 'Added Attendance Tracker & GPA Goal Planner to your Calculators hub.',
    fullMessage: 'Welcome to VTU Super App v1.2! Enjoy the new Smart Attendance Calculator with missable/required class analysis and the 3-Scenario GPA Goal Planner.',
    category: 'App',
    priority: 'Normal',
    timestamp: '4 days ago',
    date: '2026-08-30',
    isRead: true,
    targetRoute: '/(tabs)/tools',
    targetLabel: 'Explore New Calculators',
  },
];
